language: node_js
node_js:
- '0.12'
deploy:
  provider: heroku
  api_key:
    secure: kOasQVBlXAlEqM1wSSnu4MJOcdtubELah7ROI4+ax7ckpS3dOsa9MEEsPXpP9ThjN7yhuzMD4kUHqtldESC5HNxd2KMDzL7VW2EptMiFhX8oVyxMWdt/UUHNHxebODOqFRwWbrGmaQWPXOt6VLXsmtGq3BMD1MUh5ck9vGxFwVGYnSw+L/t7iuOEHRTafDdBCPImI4oyJBfBwWVt+RM+L4DV+RS1h8WfUHPcF3NEHNFnrv67sCJw58U5WVwKeIVCTbJcBBvlbWnnIPxOJxkGKoVWcK1GIqBEE5Dv275qG6JXUveZW80l8xa7FVBF2VYRqG561Ja0OUHdiuQQ91SfLiJp6BFHFXnjc4OjGaO5pZ8AEdAPdD8og47v1i4WThh+FnSBjiKDhgshldbBqRX5CyFg7wlzrmqwjndfqZOtDKhUGvGBfxItYCfzp4j6VYLxTQHsF+1V35k6YPcNyo6BCl7BuGY7klJa9Nq0gfiDXIWEncrtBM5b6UQKUh5++q9uGyfqaEyXeSiag5+YkT5w1TASR3YwxZaadYfE4w9O0eqvWQIZurM+tAKUFQlslThGRQ49sA/w/dVK0AS/EOl7MXGgrdTEy1R7hEj4xthEwpegaKADTN66HkYTKjQMikr0CjOeGvAhL5GxuWaXrC3/6EpS9Hvb76iD1IXnGojY1OA=
  app: aqueous-hamlet-8950
